var myString ="Hello World!*76";
console.log(typeof myString);
//ANYTHING IN QUOTES IN JS IS A STRING. JS ASSUMES THIS WHICH MAKES IT A LOOSELY TYPED BEFAUSE YOU DONT HAVE TO DECLARE THE TYPE OF YOUR VARIABLE.

var myNumber = 43;
console.log(typeof myNumber);
//THERE ARE CERTAIN THINGS THAT YOU CAN DO TO STRINGS THAT YOU CANT DO TO NUMBERS.

var newVariable; //THIS IS A DECLARATION. JS HAVE CARVED OUT THE SPACE IN YOUR MEMORY FOR IT. BUT IT IS UNDEFINED.
console.log(newVariable);
//UNDEFINED VARIABLE IS OK IF IT IS INTENTIONAL. NOT IF IT IS ACCIDENTAL.
//UNDEFINED MEANS, THE THING YOU ARE REFERRING TO .... ??

var isLoggedIn = true
//TRUE ISNT IN QUOTES BECAUSE IT IS A BOOLEAN.
//BEST PRACTICE FOR BOOLEAN IS TO NAME THEM INTUITIVELY, LIKE "IS SOMETHING"


isLoggedIn = "null"; //THIS IS A STRING BECAUSE IT IS IN QUOTES.

isLoggedIn = null; //THIS IS NULL. 
